
        /*
         *  THIS FILE IS AUTOMATICALLY GENERATED IN SETTINGS PANEL OF ACE PLUGIN
         *  IT SHOULD BE WRITABLE FOR PHP - chmod 0777
         *  DO NOT MODIFY THESE SETTINGS MANUALLY
         */

        var aceMode = "php";
        var aceStrMode = "Mode";
        var aceStrConfig = "Config";
        var aceTheme = "monokai";
        var aceFontSize = 13;
        var aceScrollSpeed = 6;
        var aceEditorHeight = 400;
        var aceWrapLines = true;
        var aceWrapRange = 80;
        var aceLayoutIntegrate = true;
        var aceCookieLife = 365;
        var aceHighlightActiveLine = true;
        