
        /*
         *  THIS FILE IS AUTOMATICALLY GENERATED IN SETTINGS PANEL OF ACE PLUGIN
         *  IT SHOULD BE WRITABLE FOR PHP - chmod 0777
         *  DO NOT MODIFY THESE SETTINGS MANUALLY
         */
           
        var aceMode = "php";
        var aceTheme = "merbivore";
        var aceFontSize = 12;
        var aceScrollSpeed = 6;
        var aceEditorHeight = 420;
        var aceWrapLines = true;
        var aceWrapRange = 52;
        var aceLayoutIntegrate = true;
        