
        /*
         *  THIS FILE IS AUTOMATICALLY GENERATED IN SETTINGS PANEL OF ACE PLUGIN
         *  IT SHOULD BE WRITABLE FOR PHP - chmod 0777
         *  DO NOT MODIFY THESE SETTINGS MANUALLY
         */
           
        var aceMode = "php";
        var aceTheme = "monokai";
        var aceFontSize = 12;
        var aceScrollSpeed = 6;
        var aceEditorHeight = 400;
        var aceWrapLines = true;
        var aceWrapRange = 80;
        var aceLayoutIntegrate = true;
        var aceCookieLife = 365;
        